#source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'XNNetWorkManager_Example' do
  pod 'XNNetWorkManager', :path => '../'

  target 'XNNetWorkManager_Tests' do
    inherit! :search_paths

    
  end
end
